[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["data/playlists/fifa-channel.m3u8"]

[functions."___netlify-server-handler"]
  timeout = 26
